#!/bin/bash
set -e

# Apache gets grumpy about PID files pre-existing
rm -f /var/run/apache2/apache2.pid

# exec apache2 -DFOREGROUND
source /etc/apache2/envvars && exec /usr/sbin/apache2 -DFOREGROUND